### ISSUE TITLE
Add unit testing to api-tools

### ISSUE THREAD

**Issue by jpahm** [UTDNebula/api-tools#22]
**The toolkit would greatly benefit from both unit and integration testing, and ideally sooner rather than later.**

We'll have to talk about how exactly we want to go about effectively performing integration testing, but unit testing should be fairly straightforward via [Go's built-in testing library](https://pkg.go.dev/testing). I would personally be in favor of the test files being within the same package as the files being tested so that non-exported methods can be tested more easily.

- [ ] Create unit tests for all existing non-elementary parts of the toolkit

Any comments on this are welcome, as usual.

**Comment by TortCode** [comment]
I can work on this, starting with the unit testing at least

**Comment by jpahm** [comment]
Yeah, no worries on integration testing yet. You've got it!

**Comment by jpahm** [comment]
@TortCode Are you still working on this?

**Comment by jpahm** [comment]
Reopening this since I haven't heard any updates for a while.

**Comment by jpahm** [comment]
*Also going to bump this up to an L3 since it's a rather large undertaking at this point

**Comment by jpahm** [comment]
Closing favor of splitting into multiple smaller sub-issues.
