### ISSUE TITLE
Move initChromeDP and refreshToken methods from coursebook scraper into util methods

### ISSUE THREAD

**Issue by jpahm** [UTDNebula/api-tools#24]
Currently, the `initChromeDP` and `refreshToken` methods are part of [the coursebook scraper](https://github.com/UTDNebula/api-tools/blob/8fd0174a1966f4c44838a80c71e20771f55a7b52/scrapers/coursebook.go), despite being accessed from multiple areas within the tools. Thus, it'd make more sense for them to both be moved to be part of [the utility methods.](https://github.com/UTDNebula/api-tools/blob/develop/utils/methods.go)

Any other changes involving cleanup of commonly used functions are encouraged.

**Comment by democat3457** [comment]
Can I get assigned to this? Seems pretty simple to knock out

**Comment by jpahm** [comment]
> Can I get assigned to this? Seems pretty simple to knock out

Sure thing!

**Comment by jpahm** [comment]
@democat3457 Are you still working on this?

**Comment by democat3457** [comment]
@jpahm oh yeah, sorry about that - got busy and forgot. I'll work on it now.
