### ISSUE TITLE
Dynamically retrieve course prefix list for coursebook scraping

### ISSUE THREAD

**Issue by jpahm** [UTDNebula/api-tools#25]
Currently in [the coursebook scraper](https://github.com/UTDNebula/api-tools/blob/develop/scrapers/coursebook.go), the list of course prefixes is hardcoded in the form of an array named `coursePrefixes` defined at the end of the file. While this works for now, it isn't exactly the best solution since the school could presumably add more course prefixes at some later date.

Thus, to make this system more future-proof, we should retrieve the list of available course prefixes dynamically via scraping them directly from the coursebook prefix dropdown.

**Comment by mohammadmehrab** [comment]
I'd like to be assigned this issue please!

**Comment by jpahm** [comment]
> I'd like to be assigned this issue please!

You got it!

**Comment by jpahm** [comment]
@mohammadmehrab Are you still working on this?

**Comment by jpahm** [comment]
Re-opening this unless I hear back.

**Comment by jpahm** [comment]
**Disregard previous message

**Comment by jpahm** [comment]
Closed via #35
