### ISSUE TITLE
Get Fall 2024 Scraping Working

### ISSUE THREAD

**Issue by jpahm** [UTDNebula/api-tools#28]
The Coursebook scraper is currently failing to pass the login page, which is resulting in an inability to scrape the Fall 2024 course data. This is a priority to fix ASAP since this data is needed soon! This will require knowledge of chromedp and some good debugging skills.

**Comment by mohammadmehrab** [comment]
I'm going to try to work on this one, but I would appreciate any help or collaboration with it too! Just contact me on the Discord

**Comment by jpahm** [comment]
> I'm going to try to work on this one, but I would appreciate any help or collaboration with it too! Just contact me on the Discord

Assigned to you, let me know if you need any additional support!

**Comment by democat3457** [comment]
Is this fixed by e89f7b88c8e071b39361df51a7bb2d75eb9c2815?

**Comment by jpahm** [comment]
> Is this fixed by [e89f7b8](https://github.com/UTDNebula/api-tools/commit/e89f7b88c8e071b39361df51a7bb2d75eb9c2815)?

Yes, apologies, forgot to mark this as fixed!
