### ISSUE TITLE
Make HEADLESS_MODE toggled via CLI parameter

### ISSUE THREAD

**Issue by jpahm** [UTDNebula/api-tools#32]
Currently, `HEADLESS_MODE` for the chromedp scrapers is set via the `.env` file. However, this is a bit annoying to have to edit in order to toggle between headless and non-headless mode, so this should be changed to a command-line flag like `-headless` which can be parsed by the `main` file.

Make sure the `.env.template` file is updated accordingly.

**Comment by justi-lai** [comment]
Hey Josh, can I try taking this issue?

**Comment by jpahm** [comment]
> Hey Josh, can I try taking this issue?

Sure thing, all yours!

**Comment by justi-lai** [comment]
Thanks!

**Comment by jpahm** [comment]
Closed via #37
